// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package queries

import (
	"context"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
  id, value
) VALUES (
  $1, $2
)
`

type CreateOrderParams struct {
	ID    string
	Value []byte
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder, arg.ID, arg.Value)
	return err
}

const getNOrders = `-- name: GetNOrders :many
SELECT id, value FROM orders
LIMIT $1
`

func (q *Queries) GetNOrders(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, getNOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.ID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, value FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(&i.ID, &i.Value)
	return i, err
}
